
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
size = 7
# size = 10

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
# style = "Regular"
style = "Bold"

[general]
import = [
  # "~/.config/alacritty/themes/catppuccin_mocha.toml",
  # "~/.config/alacritty/themes/falcon.toml",
  "~/.config/alacritty/themes/github_dark_colorblind.toml",
  # "~/.config/alacritty/themes/gruvbox_dark.toml",
  # "~/.config/alacritty/themes/gruvbox_material_hard_dark.toml",
  # "~/.config/alacritty/themes/monokai_charcoal.toml",
  # "~/.config/alacritty/themes/one_dark.toml",
  # "~/.config/alacritty/themes/seashells.toml",
  # "~/.config/alacritty/themes/tokyo-night.toml",
]
